name: Prettier
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Check formatting
        run: yarn format:check
